### ISSUE TITLE
Add the permanent object URL into the $File / Embed URI field

### ISSUE THREAD

**Issue by jonjomckay** [manywho/service-s3#3]
There's currently no way to know the permanent object URL of the uploaded file, as we only return a expiring download link.

We should return the permanent URL in the `$File / Embed URI` field so that people can use it in their flows (assuming they've made the objects public).

**Comment by jonjomckay** [comment]
@josecollazzi could you review please?

**Comment by josecollazzi** [comment]
@jonjomckay  LGTM
